services:
  server:
    env_file: "api_key.env"
    build:
      target: production
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "4m"
        max-file: "5"
    ports:
      - "8008:8000"
    restart: unless-stopped
